import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { WalletConnectProvider } from "@/lib/wallet-connect";
import { SmartWalletProvider } from "@/lib/smart-wallet/SmartWalletProvider";

import { BalanceProvider } from "@/providers/BalanceProvider";
import { MeProvider } from "@/providers/MeProvider";
import ThemeProvider from "@/providers/ThemeProvider";
import { ModalProvider } from "@/providers/WcEventsProvider";
import { ModalOnWCEvent } from "@/lib/wallet-connect/DialogOnWcEvent";

import { Toaster } from "@/components/ui/toaster";

const font = localFont({ src: "../public/fonts/space.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MeProvider>
            <WalletConnectProvider>
              <BalanceProvider>
                <SmartWalletProvider>
                  <ModalProvider>
                    <ModalOnWCEvent>{children}</ModalOnWCEvent>
                  </ModalProvider>
                  <Toaster />
                </SmartWalletProvider>
              </BalanceProvider>
            </WalletConnectProvider>
          </MeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
